language: java
# Make NetworkTables happy
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - junit4
  code_climate:
          repo_token: 3196bfa644b36e30bf8c3d41c51d36d7eb39fc0d54739268ffc677170d1b26d0
before_install:
  - chmod +x gradlew
script:
  - ./gradlew $TEST_SUITE
  
# For CodeCov
after_success:
  - ./gradlew test jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)

jdk:
- oraclejdk8
notifications:
  email: false
  slack: 4828roboeagles:qjpsMMedvSTKBq3KCmDmdAjB
cards:
  enabled:
  - master
  - development
  title: Toast
env:
  - TEST_SUITE=build
  - TEST_SUITE=check
